DROP TABLE PROGRESION_JUGADOR;
CREATE TABLE PROGRESION_JUGADOR(
    ID_JUGADOR VARCHAR2(24) PRIMARY KEY,
    NOMBRE VARCHAR2(64) NOT NULL,
    POSICION VARCHAR2(3) NOT NULL,
    GLOBAL NUMBER(3),
    RITMO NUMBER(3),
    TIRO NUMBER(3),
    PASE NUMBER(3),
    REGATE NUMBER(3),
    DEFENSA NUMBER(3),
    FISICO NUMBER(3));