SET SERVEROUTPUT ON
ACCEPT PSEUDOSTRING PROMPT 'Introduzca el nombre del jugador';
DECLARE
    number_loop number(1);
    ID_ VARCHAR2(24);
    NOMBRE_ VARCHAR2(64);
    POSITION_ VARCHAR(3);
    GLOBAL_ NUMBER(3);
    RITMO_ NUMBER(3);
    TIRO_ NUMBER(3);
    PASE_ NUMBER(3);
    REGATE_ NUMBER(3);
    DEFENSA_ NUMBER(3);
    FISICO_ NUMBER(3);
BEGIN
    SELECT COUNT(*)
    INTO number_loop
    FROM JUGADORES
    WHERE NOMBRE='&PSEUDOSTRING';
    DBMS_OUTPUT.PUT_LINE('numero veces' || number_loop);
    
    SELECT POSICION, GLOBAL, RITMO, TIRO, PASE, REGATE, DEFENSA, FISICO
    INTO POSITION_, GLOBAL_, RITMO_, TIRO_, PASE_, REGATE_, DEFENSA_, FISICO_
    FROM JUGADORES
    WHERE NOMBRE='&PSEUDOSTRING';
END;
/
