ACCEPT pseudovar PROMPT 'Introduzca el numero del socio'
SET SERVEROUTPUT ON
DECLARE
    NOMBRE SOCIO.NOMBRE_COMPLETO%TYPE;
BEGIN
    SELECT NOMBRE_COMPLETO
    INTO NOMBRE
    FROM SOCIO
    WHERE ID_SOCIO=&pseudovar;
    DBMS_OUTPUT.PUT_LINE('El socio es ' || NOMBRE);
END;
/
