SET SERVEROUTPUT ON
DECLARE
    new_socio NUMBER(1);
    id_match VARCHAR2(20);
    goles_local NUMBER(2);
    goles_visitante NUMBER(2);
    valor FLOAT;
BEGIN
    SELECT ID_SOCIO
    INTO new_socio
    FROM PARTICIPANTES P
    HAVING SUM(VALOR_APUESTA)=(SELECT MAX(SUM(VALOR_APUESTA)) FROM PARTICIPANTES GROUP BY ID_SOCIO)
    GROUP BY P.ID_SOCIO;
    DBMS_OUTPUT.PUT_LINE('SOCIO ' || new_socio);
    
    SELECT ID_PARTIDO
    INTO id_match
    FROM PARTIDO
    WHERE EQUIPO_1 LIKE 'Cordoba' AND DIA_PARTIDO=(SELECT MIN(DIA_PARTIDO) FROM PARTIDO WHERE EQUIPO_1 LIKE 'Cordoba');
    DBMS_OUTPUT.PUT_LINE('ID PARTIDO ' || id_match);
    
    SELECT GOLES_1
    INTO goles_local
    FROM PARTICIPANTES p
    WHERE p.GOLES_1=(SELECT MAX(GOLES_1) FROM PARTICIPANTES)
    HAVING COUNT(p.GOLES_1)=(SELECT MAX(COUNT(GOLES_1)) FROM PARTICIPANTES GROUP BY GOLES_1) 
    GROUP BY p.GOLES_1;
    DBMS_OUTPUT.PUT_LINE('GOLES LOCAL: ' || goles_local);
    
    SELECT GOLES_2
    INTO goles_visitante
    FROM PARTICIPANTES p
    HAVING COUNT(p.GOLES_2)=(SELECT MAX(COUNT(GOLES_2)) FROM PARTICIPANTES GROUP BY GOLES_2) 
    GROUP BY p.GOLES_2;
    DBMS_OUTPUT.PUT_LINE('GOLES VISITANTE: ' || goles_visitante);
    
    SELECT DISTINCT VALOR_APUESTA
    INTO valor
    FROM PARTICIPANTES
    WHERE VALOR_APUESTA=(SELECT MAX(VALOR_APUESTA) FROM PARTICIPANTES);
    DBMS_OUTPUT.PUT_LINE('VALOR APUESTA: ' || valor);
    
    INSERT INTO PARTICIPANTES VALUES(17, new_socio, id_match, goles_local, goles_visitante, SYSDATE, valor, 1, '1');
END;