SELECT GOLES_2
FROM PARTICIPANTES p
--WHERE p.GOLES_2=(SELECT MAX(GOLES_2) FROM PARTICIPANTES)
HAVING COUNT(p.GOLES_2)=(SELECT MAX(COUNT(GOLES_2)) FROM PARTICIPANTES GROUP BY GOLES_2) 
GROUP BY p.GOLES_2;