CREATE TABLE USUARIOS(	
     NOMBRE    VARCHAR2(12) NOT NULL, 
     APELLIDOS VARCHAR2(30) NOT NULL, 
	 NICK VARCHAR2(20) NOT NULL PRIMARY KEY,
	 NOMBRE_CLUB VARCHAR2(20) NOT NULL, 
	 FECHA_FUNDACION DATE NOT NULL);
INSERT INTO USUARIOS VALUES('Daniel', 'Ranchal', 'danitico', 'Butanero', '02-11-19');
INSERT INTO USUARIOS VALUES('Juan', 'Ranchal', 'danitic', 'Butaner', '02-11-19');
