DROP TABLE jugadoresTOP;
CREATE TABLE jugadoresTOP(
    ID_JUGADOR VARCHAR2(24) PRIMARY KEY,
    NOMBRE VARCHAR2(64) NOT NULL,
    POSICION VARCHAR2(3) NOT NULL,
    GLOBAL NUMBER(3),
    RITMO NUMBER(3),
    TIRO NUMBER(3), 
    PASE NUMBER(3), 
    REGATE NUMBER(3),
    DEFENSA NUMBER(3),
    FISICO NUMBER(3),
    CONSTRAINT global_CK CHECK (GLOBAL < 100),
    CONSTRAINT ritmo_CK CHECK (RITMO < 100),
    CONSTRAINT tiro_CK CHECK (TIRO < 100),
    CONSTRAINT pase_CK CHECK (PASE < 100),
    CONSTRAINT regate_CK CHECK (REGATE < 100),
    CONSTRAINT defensa_CK CHECK (DEFENSA < 100),
    CONSTRAINT fisico_CK CHECK (FISICO < 100));