SELECT ID_SOCIO, SUM(PREMIO), CASE 
    WHEN ID_SOCIO = ANY(SELECT DISTINCT ID_SOCIO FROM PARTICIPANTES WHERE ID_SOCIO !=2) THEN SUM(PREMIO)+(SELECT SUM(PREMIO) FROM PARTICIPANTES WHERE ID_SOCIO=2)/((SELECT COUNT (DISTINCT ID_SOCIO) FROM PARTICIPANTES)-1)
    ELSE 0
    END
    "Nuevo"           
FROM PARTICIPANTES
GROUP BY ID_SOCIO
ORDER BY ID_SOCIO;


