SELECT NOMBRE_COMPLETO "Nombre"
FROM SOCIO, PARTICIPANTES
WHERE SOCIO.ID_SOCIO=PARTICIPANTES.ID_SOCIO
HAVING SUM(PREMIO) > (SELECT SUM(PREMIO) FROM PARTICIPANTES WHERE PARTICIPANTES.ID_SOCIO='3')
GROUP BY NOMBRE_COMPLETO
ORDER BY SUM(PREMIO);
