SELECT s.NOMBRE_COMPLETO, CASE 
    WHEN p.ID_SOCIO = ANY(SELECT DISTINCT ID_SOCIO FROM PARTICIPANTES WHERE ID_SOCIO !=2) THEN SUM(PREMIO)+(SELECT SUM(PREMIO) FROM PARTICIPANTES WHERE ID_SOCIO=2)/((SELECT COUNT (DISTINCT ID_SOCIO) FROM PARTICIPANTES)-1)
    ELSE 0
    END AS "NUEVO"
FROM PARTICIPANTES p, SOCIO s
WHERE s.ID_SOCIO=p.ID_SOCIO
GROUP BY p.ID_SOCIO, s.NOMBRE_COMPLETO
HAVING
CASE 
    WHEN p.ID_SOCIO = ANY(SELECT DISTINCT ID_SOCIO FROM PARTICIPANTES WHERE ID_SOCIO !=2) THEN SUM(PREMIO)+(SELECT SUM(PREMIO) FROM PARTICIPANTES WHERE ID_SOCIO=2)/((SELECT COUNT (DISTINCT ID_SOCIO) FROM PARTICIPANTES)-1)
    ELSE 0
    END > 0
ORDER BY SUM(PREMIO);

